name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23lig3bTXpZHrPO1c8"
GITHUB_OWNER = "cj7633"
GITHUB_REPO = "navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-3vz.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-3vz.pages.dev"

