name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23liP9oZwJZe8N5HNw"
GITHUB_OWNER = "cj7633"
GITHUB_REPO = "navsphere-demo"
GITHUB_BRANCH = "f9ba36c"
NEXTAUTH_URL = "https://859611a1.navsphere-3vz.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://859611a1.navsphere-3vz.pages.dev"

